
/** Hierarchy */
export const CREATE_HIERARCHY = 'CREATE_HIERARCHY';
export const CHECK_HIERARCHY_ITEM = 'CHECK_HIERARCHY_ITEM';
export const DISPLAY_HIERARCHY_CHILDREN = 'DISPLAY_HIERARCHY_CHILDREN';

/** Map */
export const CREATE_MAP_AREAS = 'CREATE_MAP_AREAS'