export const SET_HIERARCHY = 'SET_HIERARCHY';
export const GET_HIERARCHY = 'GET_HIERARCHY';
export const CREATE_HIERARCHY = 'CREATE_HIERARCHY';
export const SEARCH_HIERARCHY_ELEMENT = 'SEARCH_HIERARCHY_ELEMENT';
