export const URL = {
    home: '/',
    map: '/map',
    menu: '/menu',
    posts: '/posts',
    texts: '/texts'
}

export const Languages = [{ code: 'es', display: 'Español' }, { code: 'en', display: 'English' }];

export const menuData = {
    value: "22-hierarchy",
    label: "JERARQUÍA MIGRACIÓN NO TOCAR",
    type: "hierarchy",
    id: 22,
    children: [
        {
            label: "ALBALAT DELS SORELLS",
            value: "3598-dma",
            icon: "dma",
            favourite: true,
            sensorizable: true,
            id: 3598,
            parentId: null,
            tag: null,
            children: [
                {
                    label: "AYUNTAMIENTO",
                    value: "3599-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 3599,
                    parentId: 3598,
                    tag: null,
                    children: [

                    ]
                },
                {
                    label: "INDUSTRIAL",
                    value: "3600-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 3600,
                    parentId: 3598,
                    tag: null,
                    children: [

                    ]
                },
                {
                    label: "MESTRE SERRANO",
                    value: "3601-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 3601,
                    parentId: 3598,
                    tag: null,
                    children: [

                    ]
                },
                {
                    label: "PLANTA OSMOSIS",
                    value: "3602-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 3602,
                    parentId: 3598,
                    tag: null,
                    children: [

                    ]
                },
                {
                    label: "RIEGO PLANTA",
                    value: "3603-dma",
                    icon: "dma",
                    favourite: false,
                    sensorizable: true,
                    id: 3603,
                    parentId: 3598,
                    tag: null,
                    children: [

                    ]
                },
                {
                    label: "Otros",
                    value: "1-tag",
                    icon: "tag",
                    favourite: false,
                    sensorizable: false,
                    id: 5,
                    parentId: null,
                    tag: null,
                    children: [
                        {
                            label: "ATUNTAMIENTO + MTRO SERRANO",
                            value: "3611-dma",
                            icon: "sensor",
                            favourite: false,
                            sensorizable: true,
                            id: 3611,
                            parentId: 3598,
                            tag: {
                                id: 5,
                                name: "Otros",
                                autogenerated: null
                            },
                            children: [

                            ]
                        },
                        {
                            label: "CASCO URBANO",
                            value: "3615-dma",
                            icon: "sensor",
                            favourite: false,
                            sensorizable: true,
                            id: 3615,
                            parentId: 3598,
                            tag: {
                                id: 5,
                                name: "Otros",
                                autogenerated: null
                            },
                            children: [

                            ]
                        },
                        {
                            label: "DERIVACION AALTA C/MAR",
                            value: "3616-dma",
                            icon: "sensor",
                            favourite: false,
                            sensorizable: true,
                            id: 3616,
                            parentId: 3598,
                            tag: {
                                id: 5,
                                name: "Otros",
                                autogenerated: null
                            },
                            children: [

                            ]
                        },
                        {
                            label: "DERIVACION AALTA C/VALENCIA",
                            value: "3617-dma",
                            icon: "sensor",
                            favourite: false,
                            sensorizable: true,
                            id: 3617,
                            parentId: 3598,
                            tag: {
                                id: 5,
                                name: "Otros",
                                autogenerated: null
                            },
                            children: [

                            ]
                        }
                    ]
                },
                {
                    label: "Contadores Municipales",
                    value: "2-tag",
                    icon: "tag",
                    favourite: false,
                    sensorizable: false,
                    id: 7,
                    parentId: null,
                    tag: null,
                    children: [
                        {
                            label: "PTDA MOLINO S/N BAJO IZQ",
                            value: "3610-dma",
                            icon: "supplypoint",
                            favourite: false,
                            sensorizable: false,
                            id: 3610,
                            parentId: 3598,
                            tag: {
                                id: 7,
                                name: "Contadores Municipales",
                                autogenerated: null
                            },
                            children: [

                            ]
                        },
                        {
                            label: "PTDA MOLINO S/N BAJO IZQ",
                            value: "3899-dma",
                            icon: "supplypoint",
                            favourite: false,
                            sensorizable: false,
                            id: 3899,
                            parentId: 3598,
                            tag: {
                                id: 7,
                                name: "Contadores Municipales",
                                autogenerated: null
                            },
                            children: [

                            ]
                        }
                    ]
                }
            ]
        }
    ]
}


